set pagesize 0    
set heading on    
set feedback off    
set trimspool on    
set linesize 32767    
set termout off    
set verify off 
set colsep ","
--CHANGE THE FILE LOCATION BELOW
define location= C:\app\

spool &location.&1._dbLinks.csv
PROMPT owner,host,username,db_link
SELECT owner,host,username,db_link from dba_db_links;

spool &location.&1._dba_hist_active_sess_history.csv 
PROMPT SNAP_ID,DBID,INSTANCE_NUMBER,SAMPLE_ID,SAMPLE_TIME,SESSION_ID,SESSION_SERIAL#,USER_ID,SQL_ID,SQL_CHILD_NUMBER,SQL_PLAN_HASH_VALUE,FORCE_MATCHING_SIGNATURE,SQL_OPCODE,PLSQL_ENTRY_OBJECT_ID,PLSQL_ENTRY_SUBPROGRAM_ID,PLSQL_OBJECT_ID,PLSQL_SUBPROGRAM_ID,SERVICE_HASH,SESSION_TYPE,SESSION_STATE,QC_SESSION_ID,QC_INSTANCE_ID,BLOCKING_SESSION,BLOCKING_SESSION_STATUS,BLOCKING_SESSION_SERIAL#,EVENT,EVENT_ID,SEQ#,P1TEXT,P1,P2TEXT,P2,P3TEXT,P3,WAIT_CLASS,WAIT_CLASS_ID,WAIT_TIME,TIME_WAITED,XID,CURRENT_OBJ#,CURRENT_FILE#,CURRENT_BLOCK#,CAPTURE_OVERHEAD,IS_CAPTURED,PROGRAM,MODULE,ACTION,CLIENT_ID,FLAGS,ECID,MACHINE,PORT
SELECT 
SNAP_ID,DBID,INSTANCE_NUMBER,SAMPLE_ID,SAMPLE_TIME,SESSION_ID,SESSION_SERIAL#,USER_ID,SQL_ID,SQL_CHILD_NUMBER,SQL_PLAN_HASH_VALUE,FORCE_MATCHING_SIGNATURE,SQL_OPCODE,PLSQL_ENTRY_OBJECT_ID,PLSQL_ENTRY_SUBPROGRAM_ID,PLSQL_OBJECT_ID,PLSQL_SUBPROGRAM_ID,SERVICE_HASH,SESSION_TYPE,SESSION_STATE,QC_SESSION_ID,QC_INSTANCE_ID,BLOCKING_SESSION,BLOCKING_SESSION_STATUS,BLOCKING_SESSION_SERIAL#,EVENT,EVENT_ID,SEQ#,P1TEXT,P1,P2TEXT,P2,P3TEXT,P3,WAIT_CLASS,WAIT_CLASS_ID,WAIT_TIME,TIME_WAITED,XID,CURRENT_OBJ#,CURRENT_FILE#,CURRENT_BLOCK#,CAPTURE_OVERHEAD,IS_CAPTURED,PROGRAM,MODULE,ACTION,CLIENT_ID,FLAGS,ECID,MACHINE,PORT from DBA_HIST_ACTIVE_SESS_HISTORY where sql_id is not null order by sample_time asc;

spool &location.&1._dba_hist_sqltext.csv
PROMPT DBID,SQL_ID,SQL_TEXT,COMMAND_TYPE
SELECT DBID,SQL_ID,SQL_TEXT,COMMAND_TYPE from dba_hist_sqltext;

spool &location.&1._gv$sqlarea.csv
PROMPT SQL_TEXT,SQL_FULLTEXT,SQL_ID,SHARABLE_MEM,PERSISTENT_MEM,RUNTIME_MEM,SORTS,VERSION_COUNT,LOADED_VERSIONS,OPEN_VERSIONS,USERS_OPENING,FETCHES,EXECUTIONS,PX_SERVERS_EXECUTIONS,END_OF_FETCH_COUNT,USERS_EXECUTING,LOADS,FIRST_LOAD_TIME,INVALIDATIONS,PARSE_CALLS,DISK_READS,DIRECT_WRITES,BUFFER_GETS,APPLICATION_WAIT_TIME,CONCURRENCY_WAIT_TIME,CLUSTER_WAIT_TIME,USER_IO_WAIT_TIME,PLSQL_EXEC_TIME,JAVA_EXEC_TIME,ROWS_PROCESSED,COMMAND_TYPE,OPTIMIZER_MODE,OPTIMIZER_COST,OPTIMIZER_ENV,OPTIMIZER_ENV_HASH_VALUE,PARSING_USER_ID,PARSING_SCHEMA_ID,PARSING_SCHEMA_NAME,KEPT_VERSIONS,ADDRESS,HASH_VALUE,OLD_HASH_VALUE,PLAN_HASH_VALUE,MODULE,MODULE_HASH,ACTION,ACTION_HASH,SERIALIZABLE_ABORTS,OUTLINE_CATEGORY,CPU_TIME,ELAPSED_TIME,OUTLINE_SID,LAST_ACTIVE_CHILD_ADDRESS,REMOTE,OBJECT_STATUS,LITERAL_HASH_VALUE,LAST_LOAD_TIME,IS_OBSOLETE,CHILD_LATCH,SQL_PROFILE,PROGRAM_ID,PROGRAM_LINE#,EXACT_MATCHING_SIGNATURE,FORCE_MATCHING_SIGNATURE,LAST_ACTIVE_TIME,BIND_DATA,TYPECHECK_MEM

SELECT SQL_TEXT,SQL_FULLTEXT,SQL_ID,SHARABLE_MEM,PERSISTENT_MEM,RUNTIME_MEM,SORTS,VERSION_COUNT,LOADED_VERSIONS,OPEN_VERSIONS,USERS_OPENING,FETCHES,EXECUTIONS,PX_SERVERS_EXECUTIONS,END_OF_FETCH_COUNT,USERS_EXECUTING,LOADS,FIRST_LOAD_TIME,INVALIDATIONS,PARSE_CALLS,DISK_READS,DIRECT_WRITES,BUFFER_GETS,APPLICATION_WAIT_TIME,CONCURRENCY_WAIT_TIME,CLUSTER_WAIT_TIME,USER_IO_WAIT_TIME,PLSQL_EXEC_TIME,JAVA_EXEC_TIME,ROWS_PROCESSED,COMMAND_TYPE,OPTIMIZER_MODE,OPTIMIZER_COST,OPTIMIZER_ENV,OPTIMIZER_ENV_HASH_VALUE,PARSING_USER_ID,PARSING_SCHEMA_ID,PARSING_SCHEMA_NAME,KEPT_VERSIONS,ADDRESS,HASH_VALUE,OLD_HASH_VALUE,PLAN_HASH_VALUE,MODULE,MODULE_HASH,ACTION,ACTION_HASH,SERIALIZABLE_ABORTS,OUTLINE_CATEGORY,CPU_TIME,ELAPSED_TIME,OUTLINE_SID,LAST_ACTIVE_CHILD_ADDRESS,REMOTE,OBJECT_STATUS,LITERAL_HASH_VALUE,LAST_LOAD_TIME,IS_OBSOLETE,CHILD_LATCH,SQL_PROFILE,PROGRAM_ID,PROGRAM_LINE#,EXACT_MATCHING_SIGNATURE,FORCE_MATCHING_SIGNATURE,LAST_ACTIVE_TIME,BIND_DATA,TYPECHECK_MEM from GV$SQLAREA;

spool &location.&1._gv$sql.csv
PROMPT SQL_TEXT,SQL_FULLTEXT,SQL_ID,SHARABLE_MEM,PERSISTENT_MEM,RUNTIME_MEM,SORTS,LOADED_VERSIONS,OPEN_VERSIONS,USERS_OPENING,FETCHES,EXECUTIONS,PX_SERVERS_EXECUTIONS,END_OF_FETCH_COUNT,USERS_EXECUTING,LOADS,FIRST_LOAD_TIME,INVALIDATIONS,PARSE_CALLS,DISK_READS,DIRECT_WRITES,BUFFER_GETS,APPLICATION_WAIT_TIME,CONCURRENCY_WAIT_TIME,CLUSTER_WAIT_TIME,USER_IO_WAIT_TIME,PLSQL_EXEC_TIME,JAVA_EXEC_TIME,ROWS_PROCESSED,COMMAND_TYPE,OPTIMIZER_MODE,OPTIMIZER_COST,OPTIMIZER_ENV,OPTIMIZER_ENV_HASH_VALUE,PARSING_USER_ID,PARSING_SCHEMA_ID,PARSING_SCHEMA_NAME,KEPT_VERSIONS,ADDRESS,TYPE_CHK_HEAP,HASH_VALUE,OLD_HASH_VALUE,PLAN_HASH_VALUE,CHILD_NUMBER,SERVICE,SERVICE_HASH,MODULE,MODULE_HASH,ACTION,ACTION_HASH,SERIALIZABLE_ABORTS,OUTLINE_CATEGORY,CPU_TIME,ELAPSED_TIME,OUTLINE_SID,CHILD_ADDRESS,SQLTYPE,REMOTE,OBJECT_STATUS,LITERAL_HASH_VALUE,LAST_LOAD_TIME,IS_OBSOLETE,CHILD_LATCH,SQL_PROFILE,PROGRAM_ID,PROGRAM_LINE#,EXACT_MATCHING_SIGNATURE,FORCE_MATCHING_SIGNATURE,LAST_ACTIVE_TIME,BIND_DATA,TYPECHECK_MEM

SELECT SQL_TEXT,SQL_FULLTEXT,SQL_ID,SHARABLE_MEM,PERSISTENT_MEM,RUNTIME_MEM,SORTS,LOADED_VERSIONS,OPEN_VERSIONS,USERS_OPENING,FETCHES,EXECUTIONS,PX_SERVERS_EXECUTIONS,END_OF_FETCH_COUNT,USERS_EXECUTING,LOADS,FIRST_LOAD_TIME,INVALIDATIONS,PARSE_CALLS,DISK_READS,DIRECT_WRITES,BUFFER_GETS,APPLICATION_WAIT_TIME,CONCURRENCY_WAIT_TIME,CLUSTER_WAIT_TIME,USER_IO_WAIT_TIME,PLSQL_EXEC_TIME,JAVA_EXEC_TIME,ROWS_PROCESSED,COMMAND_TYPE,OPTIMIZER_MODE,OPTIMIZER_COST,OPTIMIZER_ENV,OPTIMIZER_ENV_HASH_VALUE,PARSING_USER_ID,PARSING_SCHEMA_ID,PARSING_SCHEMA_NAME,KEPT_VERSIONS,ADDRESS,TYPE_CHK_HEAP,HASH_VALUE,OLD_HASH_VALUE,PLAN_HASH_VALUE,CHILD_NUMBER,SERVICE,SERVICE_HASH,MODULE,MODULE_HASH,ACTION,ACTION_HASH,SERIALIZABLE_ABORTS,OUTLINE_CATEGORY,CPU_TIME,ELAPSED_TIME,OUTLINE_SID,CHILD_ADDRESS,SQLTYPE,REMOTE,OBJECT_STATUS,LITERAL_HASH_VALUE,LAST_LOAD_TIME,IS_OBSOLETE,CHILD_LATCH,SQL_PROFILE,PROGRAM_ID,PROGRAM_LINE#,EXACT_MATCHING_SIGNATURE,FORCE_MATCHING_SIGNATURE,LAST_ACTIVE_TIME,BIND_DATA,TYPECHECK_MEM from GV$SQL;

exit
