Echo Start: WIN2012SQL2012 >> "C:\TAL_consolidation\PowerShellScripts\PerfMonTemplates\START_OUTPUT.txt"
logman start se_consolidation_WIN2012SQL2012 -s WIN2012SQL2012 >> "C:\TAL_consolidation\PowerShellScripts\PerfMonTemplates\START_OUTPUT.txt"
Echo Start: OMNILOADVM1 >> "C:\TAL_consolidation\PowerShellScripts\PerfMonTemplates\START_OUTPUT.txt"
logman start se_consolidation_OMNILOADVM1 -s OMNILOADVM1 >> "C:\TAL_consolidation\PowerShellScripts\PerfMonTemplates\START_OUTPUT.txt"
Echo Start: SERVER2003 >> "C:\TAL_consolidation\PowerShellScripts\PerfMonTemplates\START_OUTPUT.txt"
logman start se_consolidation_SERVER2003 -s SERVER2003 >> "C:\TAL_consolidation\PowerShellScripts\PerfMonTemplates\START_OUTPUT.txt"
